# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:        
  resources:
  
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: false
      settings:
        Ensure: Present
  
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: chatgpt
      directives:
        description: Install ChatGPT
        allowPrerelease: false
      settings:
        id: lencx.ChatGPT
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscodePackage
      directives:
        description: Install Visual Studio Code
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscodeInsidersPackage
      directives:
        description: Install Visual Studio Code Insiders
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode.Insiders
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: antigravity
      directives:
        description: Install Antigravity
        allowPrerelease: false
      settings:
        id: Google.Antigravity
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: kirodev
      directives:
        description: Install Kiro
        allowPrerelease: false
      settings:
        id: Amazon.Kiro
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: opencode
      directives:
        description: Install OpenCode
        allowPrerelease: false
      settings:
        id: SST.OpenCodeDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: postmanPackage
      directives:
        description: Install Postman
        allowPrerelease: false
      settings:
        id: Postman.Postman
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dotnetCore10
      directives:
        description: Install .NET Core 10 SDK
        allowPrerelease: false
      settings:
        id: Microsoft.DotNet.SDK.10
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: gitPackage
      directives:
        description: Install Git
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: githubDesktopPackage
      directives:
        description: Install GitHub Desktop
      settings:
        id: GitHub.GitHubDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: gitKraken
      directives:
        description: Install GitKraken
      settings:
        id: Axosoft.GitKraken
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nvmPackage
      directives:
        description: Install NVM for Windows
      settings:
        id: CoreyButler.NVMforWindows
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: redisInsightPackage
      directives:
        description: Install RedisInsight
      settings:
        id: XP8K1GHCB0F1R2
        source: msstore
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: sqlServerManagementStudioPackage
      directives:
        description: Install Microsoft SQL Server Management Studio (SSMS)
      settings:
        id: Microsoft.SQLServerManagementStudio
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dockerDesktopPackage
      directives:
        description: Install Docker Desktop
        allowPrerelease: false
      settings:
        id: Docker.DockerDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: rescuetime
      directives:
        description: Install RescueTime
        allowPrerelease: false
      settings:
        id: RescueTime.DesktopApp
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: notionPackage
      directives:
        description: Install Notion
        allowPrerelease: false
      settings:
        id: Notion.Notion
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nugetPackage
      directives:
        description: Install NuGet
        allowPrerelease: false
      settings:
        id: Microsoft.NuGet
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powerShellPackage
      directives:
        description: Install PowerShell
        allowPrerelease: false
      settings:
        id: Microsoft.PowerShell
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ohMyPoshPackage
      directives:
        description: Install OhMyPosh
        allowPrerelease: false
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: 7zipPackage
      directives:
        description: Install 7zip
        allowPrerelease: false
      settings:
        id: 7zip.7zip
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powerToysPackage
      directives:
        description: Install PowerToys
        allowPrerelease: false
      settings:
        id: Microsoft.PowerToys
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: sQLiteStudioPackage
      directives:
        description: Install SQLiteStudio
        allowPrerelease: false
      settings:
        id: PawelSalawa.SQLiteStudio
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: jetbrainsRiderPackage
      directives:
        description: Install JetBrains Rider
        allowPrerelease: false
      settings:
        id: JetBrains.Rider
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: edgeDevPackage
      directives:
        description: Install Edge Dev
        allowPrerelease: false
      settings:
        id: Microsoft.Edge.Dev
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: windowsTerminalPackage
      directives:
        description: Install Microsoft Windows Terminal
        allowPrerelease: false
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: discordPackage
      directives:
        description: Install Discord
        allowPrerelease: false
      settings:
        id: Discord.Discord
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: slackPackage
      directives:
        description: Install Slack
        allowPrerelease: false
      settings:
        id: SlackTechnologies.Slack
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nordPassPackage
      directives:
        description: Install Nordpass
        allowPrerelease: false
      settings:
        id: NordSecurity.NordPass
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nordVPN
      directives:
        description: Install NordVPN
        allowPrerelease: false
      settings:
        id: NordSecurity.NordVPN
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: lmStudioPackage
      directives:
        description: Install LM Studio
        allowPrerelease: false
      settings:
        id: ElementLabs.LMStudio
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: foundrylocal
      directives:
        description: Install FoundryLocal
        allowPrerelease: false
      settings:
        id: Microsoft.FoundryLocal
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: spotifyPackage
      directives:
        description: Install Spotify
        allowPrerelease: false
      settings:
        id: Spotify.Spotify
        source: winget

  configurationVersion: 0.2.0
